package bingo.admins;

import bingo.jugadores.InterfazJugadorFrame;
import bingo.modelo.exceptions.ConfiguracionNoValidaException;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Interfaz para Administradores
 * @author maurocarrero
 */
public class InterfazAdminFrame extends javax.swing.JFrame {
    
    private AdminFacade admin;
    
    /**
     * Creates new form InterfazAdmin
     */
    public InterfazAdminFrame(AdminFacade admin) {
        initComponents();
        this.admin = admin;
        this.setTitle("Bingo - Administrador");
        ocultarPaneles();
        panelLogin.setVisible(true);
        menuBar.setVisible(false);
        setLocationRelativeTo(null);
        pack();
    }
    
    private void ocultarPaneles() {
        panelCrearInterfaces.setVisible(false);
        panelConfigurar.setVisible(false);
        panelLogin.setVisible(false);
    }

    private void ingresar() {
        String usuario = txtUsuario.getText();
        char[] password = txtPassword.getPassword();
        if (admin.login(usuario, password)) {
            ocultarPaneles();
            menuBar.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido " + usuario + "!", "Exito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Acceso denegado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void poblarCamposConfiguracion() {
        txtCantFilas.setText("" + admin.getCantFilas());
        txtCantColumnas.setText("" + admin.getCantColumnas());
        txtCantMaxCartones.setText("" + admin.getCantMaxCartones());
        txtCantJugadores.setText("" + admin.getCantJugadores());
        txtValorCarton.setText("" + admin.getValorCarton());
    }
    
    private void configurar() {
        if (!admin.hayJuegoActivo()) {
            ocultarPaneles();
            panelConfigurar.setVisible(true);
            poblarCamposConfiguracion();
            pack();
        } else {
            JOptionPane.showMessageDialog(null, "Hay un juego activo, no se puede modificar la configuración.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void lanzarNuevaInterfazJugador() {
        admin.lanzarNuevaInterfazJugador();
    }
    
    private void crearInterfaces() {
        ocultarPaneles();
        panelCrearInterfaces.setVisible(true);
        lanzarNuevaInterfazJugador();
    }
    
    private void guardarConfiguracion() {
        try {
            int cantFilas = Integer.parseInt(txtCantFilas.getText());
            int cantColumnas = Integer.parseInt(txtCantColumnas.getText());
            int cantMaxCartones = Integer.parseInt(txtCantMaxCartones.getText());
            int cantJugadores = Integer.parseInt(txtCantJugadores.getText());
            double valorCarton = Double.parseDouble(txtValorCarton.getText());
            
            admin.guardarConfiguracion(cantFilas, cantColumnas, cantMaxCartones, cantJugadores, valorCarton);
            
            JOptionPane.showMessageDialog(null, "Configuración guardada", "Exito", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException | ConfiguracionNoValidaException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Configuración no válida", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        panelConfigurar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCantFilas = new javax.swing.JLabel();
        txtCantFilas = new javax.swing.JTextField();
        lblCantColumnas = new javax.swing.JLabel();
        txtCantColumnas = new javax.swing.JTextField();
        lblCantCartones = new javax.swing.JLabel();
        txtCantMaxCartones = new javax.swing.JTextField();
        lblCantJugadores = new javax.swing.JLabel();
        txtCantJugadores = new javax.swing.JTextField();
        lblValorCarton = new javax.swing.JLabel();
        txtValorCarton = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        panelCrearInterfaces = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAdministrar = new javax.swing.JMenu();
        menuConfigurar = new javax.swing.JMenuItem();
        menuCrearInterfaces = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Configurar");

        lblCantFilas.setText("Cantidad de filas:");

        txtCantFilas.setPreferredSize(new java.awt.Dimension(10, 25));

        lblCantColumnas.setText("Cantidad de columnas:");

        txtCantColumnas.setPreferredSize(new java.awt.Dimension(10, 25));

        lblCantCartones.setText("Cantidad máxima de cartones:");

        txtCantMaxCartones.setPreferredSize(new java.awt.Dimension(10, 25));

        lblCantJugadores.setText("Cantidad de jugadores:");

        txtCantJugadores.setPreferredSize(new java.awt.Dimension(10, 25));

        lblValorCarton.setText("Valor del cartón:");

        txtValorCarton.setPreferredSize(new java.awt.Dimension(10, 25));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfigurarLayout = new javax.swing.GroupLayout(panelConfigurar);
        panelConfigurar.setLayout(panelConfigurarLayout);
        panelConfigurarLayout.setHorizontalGroup(
            panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigurarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAceptar)
                        .addGroup(panelConfigurarLayout.createSequentialGroup()
                            .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCantFilas)
                                .addComponent(lblCantColumnas)
                                .addComponent(lblCantCartones)
                                .addComponent(lblCantJugadores)
                                .addComponent(lblValorCarton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(txtCantColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantMaxCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValorCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        panelConfigurarLayout.setVerticalGroup(
            panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigurarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantFilas)
                    .addComponent(txtCantFilas, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantColumnas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantMaxCartones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantCartones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantJugadores)
                    .addComponent(txtCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorCarton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jLabel4.setText("Crear Interfaces de usuario");

        javax.swing.GroupLayout panelCrearInterfacesLayout = new javax.swing.GroupLayout(panelCrearInterfaces);
        panelCrearInterfaces.setLayout(panelCrearInterfacesLayout);
        panelCrearInterfacesLayout.setHorizontalGroup(
            panelCrearInterfacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearInterfacesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        panelCrearInterfacesLayout.setVerticalGroup(
            panelCrearInterfacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearInterfacesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        mnuAdministrar.setText("Administrar");

        menuConfigurar.setText("Configurar");
        menuConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigurarActionPerformed(evt);
            }
        });
        mnuAdministrar.add(menuConfigurar);

        menuCrearInterfaces.setText("Crear Interfaces");
        menuCrearInterfaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearInterfacesActionPerformed(evt);
            }
        });
        mnuAdministrar.add(menuCrearInterfaces);

        menuBar.add(mnuAdministrar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCrearInterfaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCrearInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        ingresar();
    }//GEN-LAST:event_txtUsuarioActionPerformed
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ingresar();             
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        ingresar();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void menuConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigurarActionPerformed
        configurar();
    }//GEN-LAST:event_menuConfigurarActionPerformed

    private void menuCrearInterfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearInterfacesActionPerformed
        crearInterfaces();
    }//GEN-LAST:event_menuCrearInterfacesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        guardarConfiguracion();        
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCantCartones;
    private javax.swing.JLabel lblCantColumnas;
    private javax.swing.JLabel lblCantFilas;
    private javax.swing.JLabel lblCantJugadores;
    private javax.swing.JLabel lblValorCarton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuConfigurar;
    private javax.swing.JMenuItem menuCrearInterfaces;
    private javax.swing.JMenu mnuAdministrar;
    private javax.swing.JPanel panelConfigurar;
    private javax.swing.JPanel panelCrearInterfaces;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField txtCantColumnas;
    private javax.swing.JTextField txtCantFilas;
    private javax.swing.JTextField txtCantJugadores;
    private javax.swing.JTextField txtCantMaxCartones;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtValorCarton;
    // End of variables declaration//GEN-END:variables
}
